# Generated by Django 2.2.4 on 2020-11-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0002_show_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
