# Generated by Django 2.2.4 on 2020-11-08 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0003_showmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowManager',
        ),
    ]
